### PR TITLE
Feature/bchd node  test harness

### PR DESCRIPTION
**Pull request by 2qx**
This PR makes it easy for a developer to get started running test against bchd.

1a. A startup script has been added to `util/` which will assure a working binary of bchd available before testing, this script is run by `pretest` by npm for yarn.
1b. Jest `globalSetup` and `globalTeardown` scripts have been added for which assure that a single regtest node is run once throughout all tests.
2. A simple test which generates a block using `bchctl` from nodejs, and verifies that the has length is 64 characters
3. bchd is run from a spawned process, closing it properly is done by `teardown`, but it also **appears** to close when jest is `ctl-C`ed

**Changes**

- The `jest` command has been changed to `test` to pick up built-in nodejs `pretest` running.  

**Possible Gotchas**

- I assumed that a symlink doesn't need a file extension in windows, from my cygwin experience. If that is not the case, issues will arise as have been been marked out with TODO in the scripts.

This was tested on linux and darwin using both npm and yarn.

Happy to make any changes. Or follow any conventions. 

closes https://github.com/mainnet-cash/mainnet-js/issues/2

### CODE REVIEW

**Comment by readcash** [comment]
LGTM! Could you resolve the conflicts please?

**Comment by readcash** [comment]
Ok, I guess I need to change jest to test in master

**Comment by 2qx** [comment]
:crossed_fingers:

**Comment by readcash** [comment]
Ok, I'm not yet sure how to fix this inside of a PR, so I'll merge and fix it in master (this jest->test thing with Github Actions).

**Pull request merged**
