### PR TITLE
Add missing package connect-timeout

### PR DESCRIPTION
**Pull request by mainnet-pat**

### CODE REVIEW

**Comment by 2qx** [comment]
So this was installed in the root package, which is where I had been starting the server from.  

The only other dependency I see at a quick glance like that is `supertest`.  It would greatly simplify the dependencies for the main library to sequester server dependencies to the server folder at this point, if it is going to be run from `generated/serve/package.json`

**Comment by mainnet-pat** [comment]
Should this generated project not be independent from the base library?
When building a docker image for rest server I do the `npm install` from serve directory. Thus `node /path/to/generated/serve/serve.js` can be run from whichever location.
The better way should be to also make the `build` target for the api server.

**Comment by 2qx** [comment]
The two projects are fairly independent now. Initially the server used a typescript fork of the generator, which was better for testing and debugging, but killed us on performance. 

I'm open to any changes as long as the tests pass.  I think there might need to be some slight refactoring in CI.yml and for `test:api` and `api:serve:cluster`. BTW,  It's probably the case that you want to have your docker call cluster.js rather than serve.js (it's just more threads)

**Comment by mainnet-pat** [comment]
> BTW, It's probably the case that you want to have your docker call cluster.js rather than serve.js (it's just more threads)

Thanks, will do

**Comment by csilence918** [comment]
Doing my best merged

**Pull request merged**
